package com.myspace.eotworkflow;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Alerts implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("User")
	private java.lang.String user;

	@org.kie.api.definition.type.Label(value = "Business Team")
	private java.lang.String businessteam;

	public Alerts() {
	}

	public java.lang.String getUser() {
		return this.user;
	}

	public void setUser(java.lang.String user) {
		this.user = user;
	}

	public java.lang.String getBusinessteam() {
		return this.businessteam;
	}

	public void setBusinessteam(java.lang.String businessteam) {
		this.businessteam = businessteam;
	}

	public Alerts(java.lang.String user, java.lang.String businessteam) {
		this.user = user;
		this.businessteam = businessteam;
	}

}