package com.myspace.eotworkflow;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class AuthorityLimits implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label("Description")
	private java.lang.String description;

	@org.kie.api.definition.type.Label("Factor")
	private java.lang.Integer factor;

	@org.kie.api.definition.type.Label("Payment")
	private java.lang.Integer payment;

	@org.kie.api.definition.type.Label("Category")
	private java.lang.String category;

	@org.kie.api.definition.type.Label("Entity")
	private java.lang.String entity;

	@org.kie.api.definition.type.Label("Limit Amount")
	private java.lang.Float limitamount;

	public AuthorityLimits() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.Integer getFactor() {
		return this.factor;
	}

	public void setFactor(java.lang.Integer factor) {
		this.factor = factor;
	}

	public java.lang.Integer getPayment() {
		return this.payment;
	}

	public void setPayment(java.lang.Integer payment) {
		this.payment = payment;
	}

	public java.lang.String getCategory() {
		return this.category;
	}

	public void setCategory(java.lang.String category) {
		this.category = category;
	}

	public java.lang.String getEntity() {
		return this.entity;
	}

	public void setEntity(java.lang.String entity) {
		this.entity = entity;
	}

	public java.lang.Float getLimitamount() {
		return this.limitamount;
	}

	public void setLimitamount(java.lang.Float limitamount) {
		this.limitamount = limitamount;
	}

	public AuthorityLimits(java.lang.String name, java.lang.String description,
			java.lang.Integer factor, java.lang.Integer payment,
			java.lang.String category, java.lang.String entity,
			java.lang.Float limitamount) {
		this.name = name;
		this.description = description;
		this.factor = factor;
		this.payment = payment;
		this.category = category;
		this.entity = entity;
		this.limitamount = limitamount;
	}

}