package com.myspace.eotworkflow;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Quote implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Sequence Num")
	private java.lang.Integer sequencenum;
	@org.kie.api.definition.type.Label("Prospect Num")
	private java.lang.Integer prospectnum;
	@org.kie.api.definition.type.Label("Customer Name")
	private java.lang.String customername;
	@org.kie.api.definition.type.Label("Option Type")
	private java.lang.String optiontype;

	@org.kie.api.definition.type.Label(value = "Syndication")
	private java.lang.Boolean syndication;

	@org.kie.api.definition.type.Label(value = "Legal Entity Code")
	private java.lang.String legalentitycode;

	public Quote() {
	}

	public java.lang.Integer getSequencenum() {
		return this.sequencenum;
	}

	public void setSequencenum(java.lang.Integer sequencenum) {
		this.sequencenum = sequencenum;
	}

	public java.lang.Integer getProspectnum() {
		return this.prospectnum;
	}

	public void setProspectnum(java.lang.Integer prospectnum) {
		this.prospectnum = prospectnum;
	}

	public java.lang.String getCustomername() {
		return this.customername;
	}

	public void setCustomername(java.lang.String customername) {
		this.customername = customername;
	}

	public java.lang.String getOptiontype() {
		return this.optiontype;
	}

	public void setOptiontype(java.lang.String optiontype) {
		this.optiontype = optiontype;
	}

	public java.lang.Boolean getSyndication() {
		return this.syndication;
	}

	public void setSyndication(java.lang.Boolean syndication) {
		this.syndication = syndication;
	}

	public java.lang.String getLegalentitycode() {
		return this.legalentitycode;
	}

	public void setLegalentitycode(java.lang.String legalentitycode) {
		this.legalentitycode = legalentitycode;
	}

	public Quote(java.lang.Integer sequencenum, java.lang.Integer prospectnum,
			java.lang.String customername, java.lang.String optiontype,
			java.lang.Boolean syndication, java.lang.String legalentitycode) {
		this.sequencenum = sequencenum;
		this.prospectnum = prospectnum;
		this.customername = customername;
		this.optiontype = optiontype;
		this.syndication = syndication;
		this.legalentitycode = legalentitycode;
	}

}