package com.myspace.eotworkflow;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Risk implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Risk() {
    }




}